package main

import (
	"context"
	"flag"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/hovsep/fmesh"
	"github.com/hovsep/fmesh-examples/internal"
	"github.com/hovsep/fmesh-export/dot"
	"github.com/hovsep/fmesh/component"
	"github.com/hovsep/fmesh/cycle"
	"github.com/hovsep/fmesh/signal"
)

// A tree where every node is a component: a company's org chart, generated by
// a loop, 31 people deep in five levels. A search starts at the top and goes
// down as a wave: every person on the same level checks at the same time, in
// the same cycle. The answers come back up the same way, each manager merging
// their reports' answers with their own, until the CEO holds the result.
//
// However many people work there, a search takes as many cycles as the
// chart has levels (twice: down and back up), not as many as it has people.
//
// Run: go run .   (add -frames out/ to write one highlighted graph per cycle)

const (
	portQuery   = "query"   // the question, from the manager
	portDown    = "down"    // the question, to every report
	portAnswers = "answers" // the answer of this whole subtree, to the manager
)

// Person is one node of the org chart.
type Person struct {
	Name    string
	Title   string
	Skills  []string
	Reports []*Person
}

// Query is what travels down: the skill being looked for.
type Query struct {
	Skill string
}

// Answer is what travels up: who in a subtree has the skill, and how many
// people were asked.
type Answer struct {
	Found []string
	Asked int
}

func main() {
	frames := flag.String("frames", "", "directory to write one activation-highlighted DOT graph per cycle into")
	flag.Parse()

	fmt.Println("=== Tree Search ===")
	fmt.Println("An org chart where every person is a component; a search is a wave through it.")
	fmt.Println()

	company := orgChart(4)
	fm, err := getMesh(company)
	if err != nil {
		fmt.Println("Failed to build mesh:", err)
		os.Exit(1)
	}

	handled, err := internal.HandleGraphFlag(fm)
	if err != nil {
		fmt.Println("Failed to generate graph:", err)
		os.Exit(1)
	}
	if handled {
		return
	}

	// The tree is built once and asked many times.
	for _, skill := range []string{"Go", "Rust"} {
		if err := ask(fm, company, skill, *frames); err != nil {
			fmt.Println("Search failed:", err)
			os.Exit(1)
		}
	}

	// Pipes are fixed once a mesh is built, so a change to the tree means a
	// new mesh. Cheap: it is the same loop, run again.
	fmt.Println("Ivy takes on a Go intern. The chart grows a sixth level, so the mesh is rebuilt:")
	ivy := find(company, "Ivy")
	ivy.Reports = append(ivy.Reports, &Person{Name: "Zed", Title: "Intern", Skills: []string{"Go"}})
	fm, err = getMesh(company)
	if err != nil {
		fmt.Println("Failed to rebuild mesh:", err)
		os.Exit(1)
	}
	if err := ask(fm, company, "Go", ""); err != nil {
		fmt.Println("Search failed:", err)
		os.Exit(1)
	}
}

// ask runs one search and prints how the wave went through the tree.
func ask(fm *fmesh.FMesh, company *Person, skill, framesDir string) error {
	level := levels(company)

	fmt.Printf("Who knows %s?\n", skill)
	if err := fm.ComponentByName(company.Name).InputByName(portQuery).PutSignals(signal.New(Query{Skill: skill})); err != nil {
		return err
	}
	info, err := fm.Run(context.Background())
	if err != nil {
		return err
	}

	for _, c := range info.Cycles.All() {
		results := c.ActivationResults()
		if results.IsEmpty() {
			continue
		}
		byLevel := map[int]int{}
		waiting := 0
		for _, r := range results.AllOrdered() {
			if component.IsWaitingForInput(r) {
				waiting++
				continue
			}
			byLevel[level[r.ComponentName()]]++
		}
		parts := make([]string, 0)
		for _, l := range slices.Sorted(maps.Keys(byLevel)) {
			parts = append(parts, fmt.Sprintf("%d on level %d", byLevel[l], l))
		}
		if waiting > 0 {
			parts = append(parts, fmt.Sprintf("%d waiting for more reports", waiting))
		}
		fmt.Printf("  cycle %2d: %s\n", c.Number(), strings.Join(parts, ", "))

		if framesDir != "" {
			if err := writeFrame(fm, c, skill, framesDir); err != nil {
				return err
			}
		}
	}

	answer, err := fm.ComponentByName(company.Name).OutputByName(portAnswers).Signals().FirstAs[Answer]()
	if err != nil {
		return err
	}
	fmt.Printf("  → %d of %d people, found in %d cycles: %s\n\n",
		len(answer.Found), answer.Asked, info.Cycles.Len()-1, strings.Join(answer.Found, ", "))
	return nil
}

// getMesh turns the org chart into a mesh: one component per person, a pipe
// down to every report and one back up. The shape comes from the data; there
// is no wiring by hand.
func getMesh(root *Person) (*fmesh.FMesh, error) {
	fm, err := fmesh.New("org chart",
		fmesh.WithDescription("a tree of people: questions go down level by level, answers come back up"),
	)
	if err != nil {
		return nil, err
	}

	var add func(p *Person) (*component.Component, error)
	add = func(p *Person) (*component.Component, error) {
		node, err := newPerson(p)
		if err != nil {
			return nil, err
		}
		if err := fm.AddComponents(node); err != nil {
			return nil, err
		}
		for _, r := range p.Reports {
			report, err := add(r)
			if err != nil {
				return nil, err
			}
			if err := node.OutputByName(portDown).PipeTo(report.InputByName(portQuery)); err != nil {
				return nil, err
			}
			if err := report.OutputByName(portAnswers).PipeTo(node.InputByName(r.Name)); err != nil {
				return nil, err
			}
		}
		return node, nil
	}
	_, err = add(root)
	return fm, err
}

// newPerson is one node. It has an input per direct report, named after them.
//
// When the question arrives it passes it down to every report and notes its
// own answer. When the reports' answers have all arrived, it merges them with
// its own and sends the lot up. Someone with no reports answers at once.
func newPerson(p *Person) (*component.Component, error) {
	reports := make([]string, len(p.Reports))
	for i, r := range p.Reports {
		reports[i] = r.Name
	}

	answerUp := func(this *component.Component, own Answer) error {
		merged := Answer{Found: slices.Clone(own.Found), Asked: own.Asked}
		for _, name := range reports {
			sub, err := this.InputByName(name).Signals().FirstAs[Answer]()
			if err != nil {
				return err
			}
			merged.Found = append(merged.Found, sub.Found...)
			merged.Asked += sub.Asked
		}
		return this.OutputByName(portAnswers).PutSignals(signal.New(merged))
	}

	return component.New(p.Name,
		component.WithDescription(fmt.Sprintf("%s · %s", p.Title, strings.Join(p.Skills, ", "))),
		component.WithInputs(append([]string{portQuery}, reports...)...),
		component.WithOutputs(portDown, portAnswers),
		component.WithActivationFunc(func(ctx context.Context, this *component.Component) error {
			if this.InputByName(portQuery).HasSignals() {
				q, err := this.InputByName(portQuery).Signals().FirstAs[Query]()
				if err != nil {
					return err
				}
				own := Answer{Asked: 1}
				if slices.Contains(p.Skills, q.Skill) {
					own.Found = []string{fmt.Sprintf("%s (%s)", p.Name, p.Title)}
				}
				if len(reports) == 0 {
					return answerUp(this, own)
				}
				this.State().Set("own", own)
				return this.OutputByName(portDown).PutSignals(signal.New(q))
			}

			// Answers from below. Subtrees of different depth answer in
			// different cycles: keep the early ones and wait for the rest.
			if err := component.RequireInputs(reports...)(ctx, this); err != nil {
				return err
			}
			own, err := this.State().GetTyped[Answer]("own")
			if err != nil {
				return err
			}
			return answerUp(this, own)
		}),
	)
}

// orgChart generates a company `depth` levels below the CEO, every manager
// with two reports. Names and skills are deterministic, so every run is the
// same company.
func orgChart(depth int) *Person {
	names := strings.Fields(`Ada Bea Cyd Dan Eve Fay Gus Hal Ivy Jon Kai Lea Max Nia Oli Pam
		Quinn Ray Sam Tia Uma Vic Wes Xia Yan Zoe Abe Bo Cal Dee Eli`)
	titles := []string{"CEO", "VP", "Director", "Manager", "Engineer"}
	pool := []string{"Go", "Rust", "SQL", "Kubernetes", "Python", "React", "Java"}

	next := 0
	var grow func(level int) *Person
	grow = func(level int) *Person {
		i := next
		next++
		p := &Person{
			Name:   names[i],
			Title:  titles[min(level, len(titles)-1)],
			Skills: []string{pool[i%len(pool)]},
		}
		if second := pool[(i*3+2)%len(pool)]; second != p.Skills[0] {
			p.Skills = append(p.Skills, second)
		}
		if level < depth {
			p.Reports = []*Person{grow(level + 1), grow(level + 1)}
		}
		return p
	}
	return grow(0)
}

// levels maps every person's name to their depth in the chart.
func levels(root *Person) map[string]int {
	level := map[string]int{}
	var walk func(p *Person, l int)
	walk = func(p *Person, l int) {
		level[p.Name] = l
		for _, r := range p.Reports {
			walk(r, l+1)
		}
	}
	walk(root, 0)
	return level
}

func find(p *Person, name string) *Person {
	if p.Name == name {
		return p
	}
	for _, r := range p.Reports {
		if found := find(r, name); found != nil {
			return found
		}
	}
	return nil
}

// writeFrame writes the graph of one cycle, its active components
// highlighted, so the wave can be watched frame by frame.
func writeFrame(fm *fmesh.FMesh, c *cycle.Cycle, skill, dir string) error {
	graph, err := dot.New().ExportCycle(fm, c)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("%s-cycle-%02d.dot", strings.ToLower(skill), c.Number())), graph, 0o644)
}
